# Dataset creation settings
input_html_file: "isef_list_page.html"
output_csv_file: "isef_projects.csv"
base_url: "https://abstracts.societyforscience.org"
table_id: "tblAbstractSearchResults"

# Scraping settings
max_connections: 10
request_timeout: 60
css_selector: ".col-sm-12 > p:nth-child(6)"
max_retries: 3
retry_delay: 1
concurrent_requests: 5